load('../../malaria_serial_interval/output/Fig1.RData')

tiff(filename='../../malaria_serial_interval/output/Fig1.tiff',width=6.5,height=5,units='in',res=150,compression='lzw')

layout(rbind(1:3,rep(4,3),rep(5,3)),heights=c(.3,.35,.35))

par(xpd=TRUE,mar=c(1.25,2,2,.5),oma=c(2,2,0,0))

xrange = c(0,365)
yrange = c(0,max(HMTP.T,HMTP.U))
plot(c(rep(0,6),HMTP.T),xaxs='i',yaxs='i',col=4,lwd=2,type='l',xlim=xrange,ylim=yrange,bty='n')
lines(c(rep(0,6),HMTP.U),xaxs='i',yaxs='i',col=2,lwd=2)
legend('topright',legend=c('Treated','Untreated'),col=c(4,2),lwd=2,bty='n')
axis(1)
mtext('A',side=3,at=0,line=.25)
mtext('LEP + HMTP',side=3,line=.25,cex=.7)
mtext('Days',side=1,line=2,cex=.7)

xrange = c(0,20)
yrange = c(0,max(EIP.kankiya,EIP.kaduna,EIP.namawala,EIP.butelgut,EIP.mean))
barplot(EIP.kankiya,space=0,xaxs='i',yaxs='i',border=NA,xlim=xrange,ylim=yrange,col=rgb(1,0,0,.25))
barplot(EIP.kaduna,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(1,.5,0,.25))
barplot(EIP.namawala,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,1,0,.25))
barplot(EIP.butelgut,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,0,1,.25))
lines(seq(xrange[1],xrange[2],.01),dnorm(seq(xrange[1],xrange[2],.01),10.475,EIP.sd),xaxs='i',yaxs='i',lwd=2)
axis(1)
mtext('B',side=3,at=0,line=.25)
mtext('EIP',side=3,line=.25,cex=.7)
mtext('Days',side=1,line=2,cex=.7)

xrange = c(0,50)
yrange = c(0,max(MHTP.kankiya,MHTP.kaduna,MHTP.namawala,MHTP.butelgut,MHTP.mean))
barplot(MHTP.kankiya,space=0,xaxs='i',yaxs='i',border=NA,xlim=xrange,ylim=yrange,col=rgb(1,0,0,.25))
barplot(MHTP.kaduna,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(1,.5,0,.25))
barplot(MHTP.namawala,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,1,0,.25))
barplot(MHTP.butelgut,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,0,1,.25))
lines(seq(xrange[1],xrange[2],.01),dexp(seq(xrange[1],xrange[2],.01),.1175),xaxs='i',yaxs='i',lwd=2)
legend(
  'topright',legend=c('Kankiya','Kaduna','Namawala','Butelgut'),
  fill=rgb(c(1,1,0,0),c(0,.5,1,1,0),c(0,0,0,1),.25),bty='n',border=rgb(c(1,1,0,0),c(0,.5,1,1,0),c(0,0,0,1),.75))
legend(22.5,.074,legend='Mean',col=1,lwd=2,bty='n')
axis(1)
mtext('C',side=3,at=0,line=.25)
mtext('MHTP',side=3,line=.25,cex=.7)
mtext('Days',side=1,line=2,cex=.7)

par(mar=c(1.25,2,3.5,.5))
xrange = c(0,365)
yrange = c(0,max(GI.T.kankiya,GI.T.kaduna,GI.T.namawala,GI.T.butelgut,GI.T.mean))
barplot(GI.T.kankiya,space=0,xaxs='i',yaxs='i',border=NA,xlim=xrange,ylim=yrange,col=rgb(1,0,0,.25))
barplot(GI.T.kaduna,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(1,.5,0,.25))
barplot(GI.T.namawala,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,1,0,.25))
barplot(GI.T.butelgut,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,0,1,.25))
lines(GI.T.kankiya,col=4,lwd=.5)
lines(GI.T.kaduna,col=4,lwd=.5)
lines(GI.T.namawala,col=4,lwd=.5)
lines(GI.T.butelgut,col=4,lwd=.5)
lines(GI.T.mean,xaxs='i',yaxs='i',lwd=2,col=4)
legend('topright',legend=c('Mean','Site-specific'),lwd=c(2,.5),col=4,bty='n')
axis(1)
mtext('D',side=3,at=0,line=.25)
mtext('Generation interval (treated)',side=3,cex=.7,line=-.5)
mtext('Density',side=2,line=2.75,cex=.7)
mtext('Days since primary infection',side=1,line=2,cex=.7)

par(mar=c(1.25,2,3.5,.5))
xrange = c(0,365)
yrange = c(0,max(GI.U.kankiya,GI.U.kaduna,GI.U.namawala,GI.U.butelgut,GI.U.mean))
barplot(GI.U.kankiya,space=0,xaxs='i',yaxs='i',border=NA,xlim=xrange,ylim=yrange,col=rgb(1,0,0,.25))
barplot(GI.U.kaduna,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(1,.5,0,.25))
barplot(GI.U.namawala,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,1,0,.25))
barplot(GI.U.butelgut,add=T,space=0,xaxs='i',yaxs='i',border=NA,col=rgb(0,0,1,.25))
lines(GI.U.kankiya,col=2,lwd=.5)
lines(GI.U.kaduna,col=2,lwd=.5)
lines(GI.U.namawala,col=2,lwd=.5)
lines(GI.U.butelgut,col=2,lwd=.5)
lines(GI.U.mean,xaxs='i',yaxs='i',lwd=2,col=2)
legend('topright',legend=c('Mean','Site-specific'),lwd=c(2,.5),col=2,bty='n')
axis(1)
mtext('E',side=3,at=0,line=.25)
mtext('Generation interval (untreated)',side=3,cex=.7,line=-.5)
mtext('Days since primary infection',side=1,line=2,cex=.7)

dev.off()
